config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :vaccines
  resources :patients
  resources :aplicators
  get '/', to: 'patients#index'
  get '/vaccines', to: 'vaccines#index'
  get '/aplicators', to: 'aplicators#index'

end

app/models/register.rb
class Register < ActiveRecord::Base
	has_many :aplicators
	has_many :patients
	has_many :vaccines
end

app/controllers/registers_controller.rb
 class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:patientId, :vaccineId, :doctorId, :dosisNumber)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patientId %><br>
    <%= f.number_field :patientId %>
  </div>
  <div class="field">
    <%= f.label :vaccineId %><br>
    <%= f.number_field :vaccineId %>
  </div>
  <div class="field">
    <%= f.label :doctorId %><br>
    <%= f.number_field :doctorId %>
  </div>
  <div class="field">
    <%= f.label :dosisNumber %><br>
    <%= f.number_field :dosisNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registers</h1>

<table>
  <thead>
    <tr>
      <th>Patientid</th>
      <th>Vaccineid</th>
      <th>Doctorid</th>
      <th>Dosisnumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.patientId %></td>
        <td><%= register.vaccineId %></td>
        <td><%= register.doctorId %></td>
        <td><%= register.dosisNumber %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New Register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patientid:</strong>
  <%= @register.patientId %>
</p>

<p>
  <strong>Vaccineid:</strong>
  <%= @register.vaccineId %>
</p>

<p>
  <strong>Doctorid:</strong>
  <%= @register.doctorId %>
</p>

<p>
  <strong>Dosisnumber:</strong>
  <%= @register.dosisNumber %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>