config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :vaccines
  resources :patients
  resources :aplicators
  get '/', to: 'patients#index'
  get '/vaccines', to: 'vaccines#index'
  get '/aplicators', to: 'aplicators#index'

end

app/models/aplicator.rb
class Aplicator < ActiveRecord::Base
	has_many :patients
end

app/controllers/aplicators_controller.rb
class AplicatorsController < ApplicationController
  before_action :set_aplicator, only: [:show, :edit, :update, :destroy]

  # GET /aplicators
  # GET /aplicators.json
  def index
    
  end

  def aplicator
    @aplicators = Aplicator.all
  end
  # GET /aplicators/1
  # GET /aplicators/1.json
  def show
  end

  # GET /aplicators/new
  def new
    @aplicator = Aplicator.new
  end

  # GET /aplicators/1/edit
  def edit
  end

  # POST /aplicators
  # POST /aplicators.json
  def create
    @aplicator = Aplicator.new(aplicator_params)

    respond_to do |format|
      if @aplicator.save
        format.html { redirect_to @aplicator, notice: 'Aplicator was successfully created.' }
        format.json { render :show, status: :created, location: @aplicator }
      else
        format.html { render :new }
        format.json { render json: @aplicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aplicators/1
  # PATCH/PUT /aplicators/1.json
  def update
    respond_to do |format|
      if @aplicator.update(aplicator_params)
        format.html { redirect_to @aplicator, notice: 'Aplicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @aplicator }
      else
        format.html { render :edit }
        format.json { render json: @aplicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aplicators/1
  # DELETE /aplicators/1.json
  def destroy
    @aplicator.destroy
    respond_to do |format|
      format.html { redirect_to aplicators_url, notice: 'Aplicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aplicator
      @aplicator = Aplicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aplicator_params
      params.require(:aplicator).permit(:name, :prefix, :clinic, :cedProf)
    end
end

app/helpers/aplicators_helper.rb
module AplicatorsHelper
end

app/views/aplicators/_form.html.erb
<%= form_for(@aplicator) do |f| %>
  <% if @aplicator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aplicator.errors.count, "error") %> prohibited this aplicator from being saved:</h2>

      <ul>
      <% @aplicator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prefix %><br>
    <%= f.text_field :prefix %>
  </div>
  <div class="field">
    <%= f.label :clinic %><br>
    <%= f.text_field :clinic %>
  </div>
  <div class="field">
    <%= f.label :cedProf %><br>
    <%= f.text_field :cedProf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aplicators/edit.html.erb
<h1>Editing Aplicator</h1>

<%= render 'form' %>

<%= link_to 'Show', @aplicator %> |
<%= link_to 'Back', aplicators_path %>

app/views/aplicators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aplicators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prefix</th>
      <th>Clinic</th>
      <th>Cedprof</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aplicators.each do |aplicator| %>
      <tr>
        <td><%= aplicator.name %></td>
        <td><%= aplicator.prefix %></td>
        <td><%= aplicator.clinic %></td>
        <td><%= aplicator.cedProf %></td>
        <td><%= link_to 'Show', aplicator %></td>
        <td><%= link_to 'Edit', edit_aplicator_path(aplicator) %></td>
        <td><%= link_to 'Destroy', aplicator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aplicator', new_aplicator_path %>

app/views/aplicators/new.html.erb
<h1>New Aplicator</h1>

<%= render 'form' %>

<%= link_to 'Back', aplicators_path %>

app/views/aplicators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @aplicator.name %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @aplicator.prefix %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @aplicator.clinic %>
</p>

<p>
  <strong>Cedprof:</strong>
  <%= @aplicator.cedProf %>
</p>

<%= link_to 'Edit', edit_aplicator_path(@aplicator) %> |
<%= link_to 'Back', aplicators_path %>