config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :vaccines
  resources :patients
  resources :aplicators
  get '/', to: 'patients#index'
  get '/vaccines', to: 'vaccines#index'
  get '/aplicators', to: 'aplicators#index'

end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
	
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  before_action :set_vaccine, only: [:show, :edit, :update, :destroy]

  # GET /vaccines
  # GET /vaccines.json
  def index
    @vaccines = Vaccine.all
  end

  # GET /vaccines/1
  # GET /vaccines/1.json
  def show
  end

  # GET /vaccines/new
  def new
    @vaccine = Vaccine.new
  end

  # GET /vaccines/1/edit
  def edit
  end

  # POST /vaccines
  # POST /vaccines.json
  def create
    @vaccine = Vaccine.new(vaccine_params)

    respond_to do |format|
      if @vaccine.save
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully created.' }
        format.json { render :show, status: :created, location: @vaccine }
      else
        format.html { render :new }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaccines/1
  # PATCH/PUT /vaccines/1.json
  def update
    respond_to do |format|
      if @vaccine.update(vaccine_params)
        format.html { redirect_to @vaccine, notice: 'Vaccine was successfully updated.' }
        format.json { render :show, status: :ok, location: @vaccine }
      else
        format.html { render :edit }
        format.json { render json: @vaccine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1
  # DELETE /vaccines/1.json
  def destroy
    @vaccine.destroy
    respond_to do |format|
      format.html { redirect_to vaccines_url, notice: 'Vaccine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaccine
      @vaccine = Vaccine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vaccine_params
      params.require(:vaccine).permit(:name, :controlNumber, :description)
    end
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/views/vaccines/_form.html.erb
<%= form_for(@vaccine) do |f| %>
  <% if @vaccine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccine.errors.count, "error") %> prohibited this vaccine from being saved:</h2>

      <ul>
      <% @vaccine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :controlNumber %><br>
    <%= f.text_field :controlNumber %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccines/edit.html.erb
<h1>Editing Vaccine</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccine %> |
<%= link_to 'Back', vaccines_path %>

app/views/vaccines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vaccines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Controlnumber</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vaccines.each do |vaccine| %>
      <tr>
        <td><%= vaccine.name %></td>
        <td><%= vaccine.controlNumber %></td>
        <td><%= vaccine.description %></td>
        <td><%= link_to 'Show', vaccine %></td>
        <td><%= link_to 'Edit', edit_vaccine_path(vaccine) %></td>
        <td><%= link_to 'Destroy', vaccine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vaccine', new_vaccine_path %>

app/views/vaccines/new.html.erb
<h1>New Vaccine</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccines_path %>

app/views/vaccines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vaccine.name %>
</p>

<p>
  <strong>Controlnumber:</strong>
  <%= @vaccine.controlNumber %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vaccine.description %>
</p>

<%= link_to 'Edit', edit_vaccine_path(@vaccine) %> |
<%= link_to 'Back', vaccines_path %>